### ISSUE TITLE
App not building (protobuf-lite and protobuf-javalite cannot coexist)

### ISSUE THREAD

**Issue by harishkthedeveloper** [espressif/esp-idf-provisioning-android#42]
> As your Esp32 code uses protobuf-lite and firebase uses protobuf-javalite  I am not able to build the code 

Now that gRPC migrated to protobuf-javalite in grpc-java 1.26, it's possible for Firebase SDKs to also migrate to protobuf-javalite.

We'll need to upgrade all SDKs at once because protobuf-lite and protobuf-javalite cannot coexist.

[https://github.com/firebase/firebase-android-sdk/issues/1152]

Please find the logs below

**Comment by harishkthedeveloper** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkSalus_appDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.protobuf.AbstractMessageLite found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.AbstractMessageLite$Builder found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.AbstractMessageLite$Builder$LimitedInputStream found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.AbstractParser found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.AbstractProtobufList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.BooleanArrayList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteBufferWriter found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteOutput found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteString found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteString$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteString$ArraysByteArrayCopier found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteString$BoundedByteString found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteString$ByteArrayCopier found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteString$ByteIterator found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteString$CodedBuilder found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteString$LeafByteString found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteString$LiteralByteString found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteString$Output found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ByteString$SystemByteArrayCopier found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.CodedInputStream found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.CodedOutputStream found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.CodedOutputStream$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.CodedOutputStream$AbstractBufferedEncoder found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.CodedOutputStream$ArrayEncoder found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.CodedOutputStream$ByteOutputEncoder found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.CodedOutputStream$OutOfSpaceException found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.CodedOutputStream$OutputStreamEncoder found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.DoubleArrayList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ExperimentalApi found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ExtensionLite found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ExtensionRegistryFactory found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ExtensionRegistryLite found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ExtensionRegistryLite$ObjectIntPair found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.FieldSet found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.FieldSet$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.FieldSet$FieldDescriptorLite found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.FloatArrayList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.GeneratedMessageLite found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.GeneratedMessageLite$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.GeneratedMessageLite$Builder found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.GeneratedMessageLite$DefaultInstanceBasedParser found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.GeneratedMessageLite$ExtendableBuilder found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.GeneratedMessageLite$ExtendableMessage found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.GeneratedMessageLite$ExtendableMessage$ExtensionWriter found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.GeneratedMessageLite$ExtendableMessageOrBuilder found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.GeneratedMessageLite$ExtensionDescriptor found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.GeneratedMessageLite$GeneratedExtension found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.GeneratedMessageLite$MethodToInvoke found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.GeneratedMessageLite$SerializedForm found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.IntArrayList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$BooleanList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$DoubleList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$EnumLite found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$EnumLiteMap found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$FloatList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$IntList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$ListAdapter found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$ListAdapter$Converter found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$LongList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$MapAdapter found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$MapAdapter$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$MapAdapter$Converter found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$MapAdapter$EntryAdapter found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$MapAdapter$IteratorAdapter found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$MapAdapter$SetAdapter found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Internal$ProtobufList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.InvalidProtocolBufferException found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.LazyField found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.LazyField$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.LazyField$LazyEntry found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.LazyField$LazyIterator found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.LazyFieldLite found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.LazyStringArrayList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.LazyStringArrayList$ByteArrayListView found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.LazyStringArrayList$ByteStringListView found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.LazyStringList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.LongArrayList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.MapEntryLite found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.MapEntryLite$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.MapEntryLite$Metadata found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.MapFieldLite found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.MessageLite found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.MessageLite$Builder found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.MessageLiteOrBuilder found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.MessageLiteToString found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.MutabilityOracle found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.MutabilityOracle$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.NioByteString found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.NioByteString$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Parser found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ProtobufArrayList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.ProtocolStringList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.RopeByteString found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.RopeByteString$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.RopeByteString$Balancer found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.RopeByteString$PieceIterator found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.RopeByteString$RopeInputStream found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.SmallSortedMap found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.SmallSortedMap$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.SmallSortedMap$EmptySet found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.SmallSortedMap$EmptySet$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.SmallSortedMap$EmptySet$2 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.SmallSortedMap$Entry found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.SmallSortedMap$EntryIterator found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.SmallSortedMap$EntrySet found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.TextFormatEscaper found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.TextFormatEscaper$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.TextFormatEscaper$2 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.TextFormatEscaper$ByteSequence found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.UninitializedMessageException found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.UnknownFieldSetLite found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.UnmodifiableLazyStringList found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.UnmodifiableLazyStringList$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.UnmodifiableLazyStringList$2 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.UnsafeUtil found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.UnsafeUtil$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Utf8 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Utf8$Processor found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Utf8$SafeProcessor found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Utf8$UnpairedSurrogateException found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.Utf8$UnsafeProcessor found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.WireFormat found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.WireFormat$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.WireFormat$FieldType found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.WireFormat$FieldType$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.WireFormat$FieldType$2 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.WireFormat$FieldType$3 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.WireFormat$FieldType$4 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.WireFormat$JavaType found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.WireFormat$Utf8Validation found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.WireFormat$Utf8Validation$1 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.WireFormat$Utf8Validation$2 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
  Duplicate class com.google.protobuf.WireFormat$Utf8Validation$3 found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

**Comment by harishkthedeveloper** [comment]
I don't know what's duplicate error, I checked I don't have duplicate class and 3.14.0 jar also I can't find ..
can any one help in solving this

**Comment by AliShehab93** [comment]
I have got the same problem and I opened an issue before you. I am still waiting till they upgrade their package. But I can't still wait till they solve it, so I go into solving it from my side. I downloaded the project and updated the dependencies in the Gradle file. And now the app is building with protobuf javalite upgrade. If you haven't found a solution, I can help you with the steps that I did.

**Comment by khushbushah2302** [comment]
@AliShehab93 ,
Can you create PR for the fix so that solution will be available to all ?

**Comment by Ivan-Daniel-Ortiz** [comment]
@AliShehab93 ,
Could you show us the steps you have followed to correct the dependencies after downloading the project?

**Comment by harishkthedeveloper** [comment]
@AliShehab93  Hi Thanks for the reply. bcz of the above issue i had to remove all firebase dependencies, but after removing also i am still not able to build the release APK bcz of ESP 32 Library it has too many deprecated stuff. as you said you updated dependencies and you are able to build the app , I would like to know how did you achieved it  ?

**Comment by khushbushah2302** [comment]
@harishkthedeveloper ,
Fixed is available now. Please check. 
Thanks for reporting the issue.

**Comment by harishkthedeveloper** [comment]
@khushbushah2302  Thank you for reply .. i will check with latest release

**Comment by harishkthedeveloper** [comment]
@khushbushah2302   lib-2.0.9 is this the version with the protobuf  fix ?

**Comment by khushbushah2302** [comment]
Yes.  lib-2.0.9 has the fix.
Let us know if you still face this issue again.

**Comment by akshitsharma** [comment]
Duplicate class com.google.android.gms.internal.vision.zzl found in modules jetified-firebase-ml-vision-face-model-17.0.2-runtime.jar (com.google.firebase:firebase-ml-vision-face-model:17.0.2) and play-services-vision-20.1.3-runtime.jar (com.google.android.gms:play-services-vision:20.1.3)

still facing this issue

**Comment by khushbushah2302** [comment]
Hi @akshitsharma ,

May I know which firebase dependencies you will require for your project ? 
I have checked with firebase analytics and it is working fine.

From your comment, maybe you are using "firebase-ml-vision-face-model". 
I tried that but found that it is deprecated so tried with new firebase ML dependency as below and it is working fine.

```
implementation platform('com.google.firebase:firebase-bom:28.0.1')
implementation 'com.google.firebase:firebase-analytics'
implementation 'com.google.firebase:firebase-ml-modeldownloader'
```

**Comment by akshitsharma** [comment]
I have implemented this espressif with mlkit model . I am using >> 
mlkitImplementation "com.google.firebase:firebase-ml-vision:${safeExtGet('firebase-ml-vision', '19.0.3')}"
mlkitImplementation "com.google.firebase:firebase-ml-vision-face-model:${safeExtGet('firebase-ml-vision-face-model', '17.0.2')}"

Conflicting with this internal libs: 
Duplicate class com.google.android.gms.internal.vision.zzl found in modules jetified-firebase-ml-vision-face-model-17.0.2-runtime.jar (com.google.firebase:firebase-ml-vision-face-model:17.0.2) and play-services-vision-20.1.3-runtime.jar (com.google.android.gms:play-services-vision:20.1.3)

Facing the above issue when integrating with mlkit firebase. Unable to build the app. My TL is troubling me alot, please help

**Comment by khushbushah2302** [comment]
This internal lib is a google's vision lib ( "com.google.android.gms:play-services-vision:20.1.3" ) and it is used for QR code scanning.
There some issues which are mention in [Firebase release note for ML Kit](https://firebase.google.com/support/release-notes/android#mlkit-self-serve-fixes).
If possible, please try to remove deprecated versions and upgrade it to latest version.

**Comment by nitinvarda** [comment]
> Yes. lib-2.0.9 has the fix.
> Let us know if you still face this issue again.

hi @khushbushah2302 , i'm facing the same issue even after updating the version to lib-2.0.9. im using @react-native-firebase/firestore and react-native-esp-idf package  in my project. react-native-esp-idf package has version lib-2.0.8 in dependencies , i have changed it to lib-2.0.9 .  but still facing the same issue.

can you please help me out to resolve this issue.

**Comment by khushbushah2302** [comment]
> > Yes. lib-2.0.9 has the fix.
> > Let us know if you still face this issue again.
> 
> hi @khushbushah2302 , i'm facing the same issue even after updating the version to lib-2.0.9. im using @react-native-firebase/firestore and react-native-esp-idf package in my project. react-native-esp-idf package has version lib-2.0.8 in dependencies , i have changed it to lib-2.0.9 . but still facing the same issue.
> 
> can you please help me out to resolve this issue.

@nitinvarda , please check this in a new version of lib (lib-2.0.10)
